### ISSUE TITLE
Error using R2019b Update 4

### ISSUE THREAD

**Issue by jzl293** [sadmankazi/QCM-D-Analysis-GUI#1]
Running QCMDAnalyze.m with the newest update (R2019b Update 4) reports the following error when you push the "Plot QCM Data" button.

Unrecognized function or variable 'exitflag'.
Error in QCMDAnalyze>plotqcmdata_Callback (line 310)
        handles.exitflag{i}(k) = exitflag;
Error in gui_mainfcn (line 95)
        feval(varargin{:});
Error in QCMDAnalyze (line 63)
    gui_mainfcn(gui_State, varargin{:});
Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)QCMDAnalyze('plotqcmdata_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

This happens with the "PMMA film in air" example spreadsheet, and does not happen when run on a 2018a version of Matlab.

**Comment by sadmankazi** [comment]
Working on fixing this issue.  Stay tuned!

**Comment by sadmankazi** [comment]
This appears to have been an isolated problem.
